name: flask38pycharm
dependencies:
alembic                   = 1.5.7
blinker                   = 1.4
ca-certificates           = 2020.10.14
certifi                   = 2020.6.20
cffi                      = 1.14.5
click                     = 7.1.2
cryptography              = 3.4.6
dnspython                 = 2.0.0
dominate                  = 2.4.0
email-validator           = 1.1.2
email_validator           = 1.1.2
flask                     = 1.1.2
flask-bootstrap           = 3.3.7.1
flask-login               = 0.5.0
flask-mail                = 0.9.1
flask-migrate             = 2.4.0
flask-moment              = 0.7.0
flask-sqlalchemy          = 2.5.1
flask-wtf                 = 0.14.3
git                       = 2.23.0
greenlet                  = 1.0.0
idna                      = 3.1
itsdangerous              = 1.1.0
jinja2                    = 2.11.3
krb5                      = 1.17.1
libpq                     = 12.2
mako                      = 1.1.4
markupsafe                = 1.1.1
openssl                   = 1.1.1k
pip                       = 21.0.1
postgresql                = 12.2
pycparser                 = 2.20
pyjwt                     = 2.0.1
python                    = 3.8.8
python-dateutil           = 2.8.1
python-editor             = 1.0.4
python_abi                = 3.8
setuptools                = 52.0.0
six                       = 1.15.0
sqlalchemy                = 1.4.2
sqlite                    = 3.35.2
tk                        = 8.6.10
vc                        = 14.2
visitor                   = 0.1.3
vs2015_runtime            = 14.27.29016
werkzeug                  = 1.0.1
wheel                     = 0.36.2
wincertstore              = 0.2
wtforms                   = 2.3.3
zlib                      = 1.2.11
